//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIC.Portal.ServicesProvider.BpmService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BpmService.IBpmService")]
    public interface IBpmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBpmService/RunService", ReplyAction="http://tempuri.org/IBpmService/RunServiceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIC.OperationResult))]
        PIC.OperationResult RunService(object opReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBpmService/RunService", ReplyAction="http://tempuri.org/IBpmService/RunServiceResponse")]
        System.Threading.Tasks.Task<PIC.OperationResult> RunServiceAsync(object opReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBpmService/ExecCommand", ReplyAction="http://tempuri.org/IBpmService/ExecCommandResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIC.OperationResult))]
        PIC.OperationResult ExecCommand(object opReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBpmService/ExecCommand", ReplyAction="http://tempuri.org/IBpmService/ExecCommandResponse")]
        System.Threading.Tasks.Task<PIC.OperationResult> ExecCommandAsync(object opReq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBpmServiceChannel : PIC.Portal.ServicesProvider.BpmService.IBpmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BpmServiceClient : System.ServiceModel.ClientBase<PIC.Portal.ServicesProvider.BpmService.IBpmService>, PIC.Portal.ServicesProvider.BpmService.IBpmService {
        
        public BpmServiceClient() {
        }
        
        public BpmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BpmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BpmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BpmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIC.OperationResult RunService(object opReq) {
            return base.Channel.RunService(opReq);
        }
        
        public System.Threading.Tasks.Task<PIC.OperationResult> RunServiceAsync(object opReq) {
            return base.Channel.RunServiceAsync(opReq);
        }
        
        public PIC.OperationResult ExecCommand(object opReq) {
            return base.Channel.ExecCommand(opReq);
        }
        
        public System.Threading.Tasks.Task<PIC.OperationResult> ExecCommandAsync(object opReq) {
            return base.Channel.ExecCommandAsync(opReq);
        }
    }
}
